name: dhs-landsat
channels:
  - conda-forge
  - defaults
dependencies:
  - attrs=20.3.0
  - boost-cpp=1.74.0
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates
  - cairo=1.16.0
  - certifi=2020.12.5
  - cfitsio=3.470
  - click=7.1.2
  - click-plugins=1.1.1
  - cligj=0.7.1
  - curl=7.71.1
  - expat=2.2.10
  - fiona=1.8.18
  - fontconfig=2.13.1
  - freetype=2.10.4
  - freexl=1.0.5
  - gdal=3.1.4
  - geopandas=0.8.2
  - geos=3.8.1
  - geotiff=1.6.0
  - gettext=0.19.8.1
  - giflib=5.2.1
  - hdf4=4.2.13
  - hdf5=1.10.6
  - icu=68.1
  - jpeg=9d
  - json-c=0.13.1
  - kealib=1.4.14
  - krb5=1.17.2
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.71.1
  - libcxx=11.0.1
  - libdap4=3.20.6
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.3
  - libgdal=3.1.4
  - libgfortran=5.0.0
  - libgfortran5=9.3.0
  - libglib=2.66.4
  - libiconv=1.16
  - libkml=1.3.0
  - liblapack=3.9.0
  - libnetcdf=4.7.4
  - libnghttp2=1.41.0
  - libopenblas=0.3.12
  - libpng=1.6.37
  - libpq=12.3
  - libspatialindex=1.9.3
  - libspatialite=5.0.0
  - libssh2=1.9.0
  - libtiff=4.2.0
  - libwebp-base=1.1.0
  - libxml2=2.9.10
  - llvm-openmp=11.0.1
  - lz4-c=1.9.3
  - munch=2.5.0
  - ncurses=6.2
  - numpy=1.19.5
  - openjpeg=2.4.0
  - openssl=1.1.1i
  - pandas=1.1.5
  - pcre=8.44
  - pip=21.0
  - pixman=0.40.0
  - poppler=0.89.0
  - poppler-data=0.4.10
  - postgresql=12.3
  - proj=7.1.1
  - pyproj=2.6.1.post1
  - python=3.6.12
  - python-dateutil=2.8.1
  - python_abi=3.6
  - pytz=2020.5
  - readline=8.0
  - rtree=0.9.7
  - scipy=1.5.3
  - setuptools=49.6.0
  - shapely=1.7.1
  - six=1.15.0
  - sqlite=3.34.0
  - tiledb=2.1.6
  - tk=8.6.10
  - tzcode
  - wheel=0.36.2
  - xerces-c=3.2.3
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.8
  - pip:
    - cachetools==4.2.1
    - cffi==1.14.4
    - chardet==4.0.0
    - future==0.18.2
    - httplib2==0.18.1
    - httplib2shim==0.0.3
    - idna==2.10
    - protobuf==3.14.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.20
    - requests==2.25.1
    - rsa==4.7
    - uritemplate==3.0.1
    - urllib3==1.26.3
